//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_phone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth
    {
        public int id { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> menu_id { get; set; }
        public Nullable<int> permission { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual role role { get; set; }
        public virtual menu menu { get; set; }
    }
}
