//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_phone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public category()
        {
            this.products = new HashSet<product>();
        }
        
        public int id { get; set; }
        [DisplayName("Name")]
        [Required(ErrorMessage ="Please enter name category")]
        public string name { get; set; }
        [DisplayName("Code")]
        [Required(ErrorMessage = "Please enter code category")]
        public string code { get; set; }
        [Required(ErrorMessage = "Please enter describe category")]
        [DisplayName("Description")]
        public string description { get; set; }
        [DisplayName("Active")]
        public Nullable<int> active { get; set; }
        [DisplayName("Create date")]
        public System.DateTime create_date { get; set; }
        [DisplayName("Update date")]
        public Nullable<System.DateTime> update_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
    }
}
