//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_phone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoice()
        {
            this.invoicedetails = new HashSet<invoicedetail>();
        }
    
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        [DisplayName("Name user")]
        [Required(ErrorMessage = "Please enter name user")]
        public string name_user { get; set; }
        [DisplayName("Phone")]
        [Required(ErrorMessage = "Please enter phone")]
        public string phone { get; set; }
        [DisplayName("Address")]
        [Required(ErrorMessage = "Please enter address")]
        public string address { get; set; }
        [DisplayName("Payment")]
        [Required(ErrorMessage = "Please enter payment")]
        public Nullable<int> payment { get; set; }
        [DisplayName("Total price")]
        [Required(ErrorMessage = "Please enter total price")]
        public Nullable<decimal> total_price { get; set; }
        [DisplayName("Status")]
        [Required(ErrorMessage = "Please enter status")]
        public Nullable<int> status { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoicedetail> invoicedetails { get; set; }
    }
}
