//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_phone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.invoicedetails = new HashSet<invoicedetail>();
            this.productdetails = new HashSet<productdetail>();
        }
        public product(int id, category category, brand brand, string name, string code, string description, decimal price, string image_url, int active)
        {
            this.id = id;
            this.category = category;
            this.brand = brand;
            this.name = name;
            this.code = code;
            this.description = description;
            this.price = price;
            this.image_url = image_url;
            this.active = active;
        }

        public product(product product)
        {
            this.id = id;
            this.category = category;
            this.brand = brand;
            this.name = name;
            this.code = code;
            this.description = description;
            this.price = price;
            this.image_url = image_url;
            this.active = active;
            this.create_date = create_date;
            this.update_date = update_date;
        }
    
        public int id { get; set; }
        [DisplayName("Category")]
        public Nullable<int> category_id { get; set; }
        [DisplayName("Brand")]
        public Nullable<int> brand_id { get; set; }
        [Required(ErrorMessage = "Please enter name product")]
        [DisplayName("Name")]
        public string name { get; set; }
        [DisplayName("Code")]
        [Required(ErrorMessage = "Please enter code product")]
        public string code { get; set; }
        [DisplayName("Description")]
        [Required(ErrorMessage = "Please enter description product")]
        public string description { get; set; }
        [DisplayName("Price")]
        public Nullable<decimal> price { get; set; }
        [DisplayName("Image")]
        public string image_url { get; set; }
        [DisplayName("Active")]
        public Nullable<int> active { get; set; }
        [DisplayName("Create date")]
        public Nullable<System.DateTime> create_date { get; set; }
        [DisplayName("Update date")]
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoicedetail> invoicedetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productdetail> productdetails { get; set; }
    }
}
